apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopify-ingress
  namespace: shopify
  annotations:
    argocd.argoproj.io/tracking-id: shopify:networking.k8s.io/Ingress:shopify/shopify-ingress
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopify-service
            port:
              number: 80
