apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopify-ingress
  namespace: shopify
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
spec:
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopify-service
            port:
              number: 80
