apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: shopify
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: shopify-migration
        image: himani1224/shopify-migration
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/shopify"
      restartPolicy: OnFailure
